[package]
name = "maze_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.37.0", features = ["ttf"] }
rand = "0.8.5"

[target.'cfg(target_os = "emscripten")'.dependencies]
emscripten-functions = "0.2.2"
